language: node_js
node_js:
 - "node"

cache: npm
before_install: cd goodmadlib-cover
script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: goodmadlib-cover/dist
 on:
   branch: master